source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!


target 'Sembly' do
  pod 'RNVectorIcons', :path => 'node_modules/react-native-vector-icons'
  
  pod 'React', path: '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'GoogleMaps'
  end
